package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"

	idsModule "github.com/kisun-bit/drpkg/ps/pci/ids"
)

var (
	// pciidsurl = "https://pci-ids.ucw.cz/v2.2/pci.ids"
	pciidsurl = "https://raw.githubusercontent.com/pciutils/pciids/refs/heads/master/pci.ids"
)

func isHex(b byte) bool {
	return ('a' <= b && b <= 'f') || ('A' <= b && b <= 'F') || ('0' <= b && b <= '9')
}

func scan(s *bufio.Scanner) ([]idsModule.Vendor, []idsModule.BaseClass) {
	var ids []idsModule.Vendor
	var baseClasses []idsModule.BaseClass

	var line string

	var currentVendor uint16
	i := -1

	for s.Scan() {
		line = s.Text()

		switch {
		case len(line) > 2 && isHex(line[0]) && isHex(line[1]):
			v, err := strconv.ParseUint(line[:4], 16, 16)
			if err != nil {
				log.Printf("Bad hex constant for vendor: %v", line[:4])
				continue
			}
			currentVendor = uint16(v)
			ids = append(ids, idsModule.Vendor{ID: uint16(v), Name: string(line[6:]), Devices: []idsModule.Device{}})
			i++

		case len(line) > 8 && currentVendor != 0 && line[0] == '\t' && isHex(line[1]) && isHex(line[3]):
			v, err := strconv.ParseUint(line[1:5], 16, 16)
			if err != nil {
				log.Printf("Bad hex constant for device: %v", line[1:5])
				continue
			}
			ids[i].Devices = append(ids[i].Devices, idsModule.Device{ID: uint16(v), Name: line[7:]})
		case strings.HasPrefix(line, "C ") && len(line) >= 7:
			items := strings.Fields(line)
			if len(items) < 3 {
				continue
			}
			baseClass, err := strconv.ParseUint(items[1], 16, 16)
			if err != nil {
				log.Printf("Bad hex constant for base class: %v", items[1])
				continue
			}
			baseClassStr := strings.Join(items[2:], " ")
			baseClasses = append(baseClasses, idsModule.BaseClass{
				ID:   uint16(baseClass),
				Name: baseClassStr,
			})
		}
	}
	return ids, baseClasses
}

func main() {
	var (
		b   []byte
		err error
		buf bytes.Buffer
	)

	resp, err := http.Get(pciidsurl)
	if err != nil {
		log.Fatalf("unable to download pciids from github:%v", err)
	}
	defer func() {
		_ = resp.Body.Close()
	}()

	b, err = io.ReadAll(resp.Body)
	if err != nil {
		log.Fatalf("unable to consume pciids body from github:%v", err)
	}

	s := bufio.NewScanner(bytes.NewReader(b))
	ids, baseClasses := scan(s)

	//
	// 头部
	//

	idsHeader := `
// Code generated by "cd ps/pci/genids;go run main.go". DO NOT EDIT.

package ids
var IDs =[]Vendor {
`

	fmt.Fprint(&buf, idsHeader)

	//
	// 硬件Id（厂商和设备）
	//

	for _, vendor := range ids {
		fmt.Fprintf(&buf, "{ID: %#04x, Name: %q, Devices: []Device{\n", vendor.ID, vendor.Name)
		for _, dev := range vendor.Devices {
			fmt.Fprintf(&buf, "{ID:%#04x, Name:%q,},\n", dev.ID, dev.Name)
		}
		fmt.Fprintf(&buf, "},\n},\n")
	}
	fmt.Fprintf(&buf, "}\n")

	//
	// 类别（BaseClass）
	//

	baseClassesHeader := `
var Classes = map[uint32]string{
`
	fmt.Fprint(&buf, baseClassesHeader)

	for _, baseClass := range baseClasses {
		fmt.Fprintf(&buf, "0x%02X: \"%s\",\n", baseClass.ID, baseClass.Name)
	}
	fmt.Fprintf(&buf, "}\n")

	p, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("unable to format source: %v", err)
	}

	err = os.WriteFile("../ids/pciids.go", p, 0o666)
}
