// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: grpc/proto/common/common_message.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FuncIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw []byte `protobuf:"bytes,1,opt,name=Raw,proto3" json:"Raw,omitempty"`
}

func (x *FuncIn) Reset() {
	*x = FuncIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_common_common_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuncIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuncIn) ProtoMessage() {}

func (x *FuncIn) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_common_common_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuncIn.ProtoReflect.Descriptor instead.
func (*FuncIn) Descriptor() ([]byte, []int) {
	return file_grpc_proto_common_common_message_proto_rawDescGZIP(), []int{0}
}

func (x *FuncIn) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type FuncOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw []byte `protobuf:"bytes,1,opt,name=Raw,proto3" json:"Raw,omitempty"`
}

func (x *FuncOut) Reset() {
	*x = FuncOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_common_common_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuncOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuncOut) ProtoMessage() {}

func (x *FuncOut) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_common_common_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuncOut.ProtoReflect.Descriptor instead.
func (*FuncOut) Descriptor() ([]byte, []int) {
	return file_grpc_proto_common_common_message_proto_rawDescGZIP(), []int{1}
}

func (x *FuncOut) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

var File_grpc_proto_common_common_message_proto protoreflect.FileDescriptor

var file_grpc_proto_common_common_message_proto_rawDesc = []byte{
	0x0a, 0x26, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1a, 0x0a, 0x06, 0x46, 0x75, 0x6e, 0x63, 0x49,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x61, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x52, 0x61, 0x77, 0x22, 0x1b, 0x0a, 0x07, 0x46, 0x75, 0x6e, 0x63, 0x4f, 0x75, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x52, 0x61, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x52, 0x61, 0x77,
	0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b,
	0x69, 0x73, 0x75, 0x6e, 0x2d, 0x62, 0x69, 0x74, 0x2f, 0x64, 0x72, 0x70, 0x6b, 0x67, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_common_common_message_proto_rawDescOnce sync.Once
	file_grpc_proto_common_common_message_proto_rawDescData = file_grpc_proto_common_common_message_proto_rawDesc
)

func file_grpc_proto_common_common_message_proto_rawDescGZIP() []byte {
	file_grpc_proto_common_common_message_proto_rawDescOnce.Do(func() {
		file_grpc_proto_common_common_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_common_common_message_proto_rawDescData)
	})
	return file_grpc_proto_common_common_message_proto_rawDescData
}

var file_grpc_proto_common_common_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_proto_common_common_message_proto_goTypes = []interface{}{
	(*FuncIn)(nil),  // 0: commonMessage.FuncIn
	(*FuncOut)(nil), // 1: commonMessage.FuncOut
}
var file_grpc_proto_common_common_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_proto_common_common_message_proto_init() }
func file_grpc_proto_common_common_message_proto_init() {
	if File_grpc_proto_common_common_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_common_common_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuncIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_common_common_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuncOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_common_common_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_proto_common_common_message_proto_goTypes,
		DependencyIndexes: file_grpc_proto_common_common_message_proto_depIdxs,
		MessageInfos:      file_grpc_proto_common_common_message_proto_msgTypes,
	}.Build()
	File_grpc_proto_common_common_message_proto = out.File
	file_grpc_proto_common_common_message_proto_rawDesc = nil
	file_grpc_proto_common_common_message_proto_goTypes = nil
	file_grpc_proto_common_common_message_proto_depIdxs = nil
}
