// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: rpc/aio/proto/svc_minirpc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GenericServiceClient is the client API for GenericService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GenericServiceClient interface {
	// 通用 RPC 调用。
	//
	// 用于执行动态注册的方法。
	Invoke(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	// 执行命令。
	//
	// 适用于短时间运行的命令。
	ExecuteCmd(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// 启动长时间运行命令。
	//
	// 返回任务句柄，后续可通过 GetStatusOfCmdTask 查询状态。
	StartCmdTask(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// 查询命令执行状态。
	GetStatusOfCmdTask(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// 终止正在运行的命令。
	KillCmdTask(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error)
	// 打开文件。
	//
	// 返回文件句柄，后续文件读写操作使用该句柄。
	OpenFile(ctx context.Context, in *OpenFileRequest, opts ...grpc.CallOption) (*OpenFileResponse, error)
	// 读取文件数据。
	//
	// 根据文件句柄和偏移读取指定长度的数据。
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	// 写入文件数据。
	//
	// 根据文件句柄和偏移写入数据。
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	// 关闭文件。
	//
	// 释放服务端维护的文件句柄资源。
	CloseFile(ctx context.Context, in *CloseFileRequest, opts ...grpc.CallOption) (*CloseFileResponse, error)
}

type genericServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGenericServiceClient(cc grpc.ClientConnInterface) GenericServiceClient {
	return &genericServiceClient{cc}
}

func (c *genericServiceClient) Invoke(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, "/aio.GenericService/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genericServiceClient) ExecuteCmd(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/aio.GenericService/ExecuteCmd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genericServiceClient) StartCmdTask(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/aio.GenericService/StartCmdTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genericServiceClient) GetStatusOfCmdTask(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/aio.GenericService/GetStatusOfCmdTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genericServiceClient) KillCmdTask(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error) {
	out := new(KillResponse)
	err := c.cc.Invoke(ctx, "/aio.GenericService/KillCmdTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genericServiceClient) OpenFile(ctx context.Context, in *OpenFileRequest, opts ...grpc.CallOption) (*OpenFileResponse, error) {
	out := new(OpenFileResponse)
	err := c.cc.Invoke(ctx, "/aio.GenericService/OpenFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genericServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, "/aio.GenericService/ReadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genericServiceClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, "/aio.GenericService/WriteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genericServiceClient) CloseFile(ctx context.Context, in *CloseFileRequest, opts ...grpc.CallOption) (*CloseFileResponse, error) {
	out := new(CloseFileResponse)
	err := c.cc.Invoke(ctx, "/aio.GenericService/CloseFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenericServiceServer is the server API for GenericService service.
// All implementations must embed UnimplementedGenericServiceServer
// for forward compatibility
type GenericServiceServer interface {
	// 通用 RPC 调用。
	//
	// 用于执行动态注册的方法。
	Invoke(context.Context, *GenericRequest) (*GenericResponse, error)
	// 执行命令。
	//
	// 适用于短时间运行的命令。
	ExecuteCmd(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// 启动长时间运行命令。
	//
	// 返回任务句柄，后续可通过 GetStatusOfCmdTask 查询状态。
	StartCmdTask(context.Context, *StartRequest) (*StartResponse, error)
	// 查询命令执行状态。
	GetStatusOfCmdTask(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// 终止正在运行的命令。
	KillCmdTask(context.Context, *KillRequest) (*KillResponse, error)
	// 打开文件。
	//
	// 返回文件句柄，后续文件读写操作使用该句柄。
	OpenFile(context.Context, *OpenFileRequest) (*OpenFileResponse, error)
	// 读取文件数据。
	//
	// 根据文件句柄和偏移读取指定长度的数据。
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	// 写入文件数据。
	//
	// 根据文件句柄和偏移写入数据。
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	// 关闭文件。
	//
	// 释放服务端维护的文件句柄资源。
	CloseFile(context.Context, *CloseFileRequest) (*CloseFileResponse, error)
	mustEmbedUnimplementedGenericServiceServer()
}

// UnimplementedGenericServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGenericServiceServer struct {
}

func (UnimplementedGenericServiceServer) Invoke(context.Context, *GenericRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedGenericServiceServer) ExecuteCmd(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCmd not implemented")
}
func (UnimplementedGenericServiceServer) StartCmdTask(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartCmdTask not implemented")
}
func (UnimplementedGenericServiceServer) GetStatusOfCmdTask(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatusOfCmdTask not implemented")
}
func (UnimplementedGenericServiceServer) KillCmdTask(context.Context, *KillRequest) (*KillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillCmdTask not implemented")
}
func (UnimplementedGenericServiceServer) OpenFile(context.Context, *OpenFileRequest) (*OpenFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenFile not implemented")
}
func (UnimplementedGenericServiceServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedGenericServiceServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedGenericServiceServer) CloseFile(context.Context, *CloseFileRequest) (*CloseFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseFile not implemented")
}
func (UnimplementedGenericServiceServer) mustEmbedUnimplementedGenericServiceServer() {}

// UnsafeGenericServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GenericServiceServer will
// result in compilation errors.
type UnsafeGenericServiceServer interface {
	mustEmbedUnimplementedGenericServiceServer()
}

func RegisterGenericServiceServer(s grpc.ServiceRegistrar, srv GenericServiceServer) {
	s.RegisterService(&GenericService_ServiceDesc, srv)
}

func _GenericService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenericRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenericServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aio.GenericService/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenericServiceServer).Invoke(ctx, req.(*GenericRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenericService_ExecuteCmd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenericServiceServer).ExecuteCmd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aio.GenericService/ExecuteCmd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenericServiceServer).ExecuteCmd(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenericService_StartCmdTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenericServiceServer).StartCmdTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aio.GenericService/StartCmdTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenericServiceServer).StartCmdTask(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenericService_GetStatusOfCmdTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenericServiceServer).GetStatusOfCmdTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aio.GenericService/GetStatusOfCmdTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenericServiceServer).GetStatusOfCmdTask(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenericService_KillCmdTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenericServiceServer).KillCmdTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aio.GenericService/KillCmdTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenericServiceServer).KillCmdTask(ctx, req.(*KillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenericService_OpenFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenericServiceServer).OpenFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aio.GenericService/OpenFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenericServiceServer).OpenFile(ctx, req.(*OpenFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenericService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenericServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aio.GenericService/ReadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenericServiceServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenericService_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenericServiceServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aio.GenericService/WriteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenericServiceServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenericService_CloseFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenericServiceServer).CloseFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aio.GenericService/CloseFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenericServiceServer).CloseFile(ctx, req.(*CloseFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GenericService_ServiceDesc is the grpc.ServiceDesc for GenericService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GenericService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aio.GenericService",
	HandlerType: (*GenericServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _GenericService_Invoke_Handler,
		},
		{
			MethodName: "ExecuteCmd",
			Handler:    _GenericService_ExecuteCmd_Handler,
		},
		{
			MethodName: "StartCmdTask",
			Handler:    _GenericService_StartCmdTask_Handler,
		},
		{
			MethodName: "GetStatusOfCmdTask",
			Handler:    _GenericService_GetStatusOfCmdTask_Handler,
		},
		{
			MethodName: "KillCmdTask",
			Handler:    _GenericService_KillCmdTask_Handler,
		},
		{
			MethodName: "OpenFile",
			Handler:    _GenericService_OpenFile_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _GenericService_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _GenericService_WriteFile_Handler,
		},
		{
			MethodName: "CloseFile",
			Handler:    _GenericService_CloseFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/aio/proto/svc_minirpc.proto",
}
